services:
  mapasculturais:
    image: softagon/mapasculturais:2025-04-05
    restart: unless-stopped
    volumes:
      - ./docker-data/assets:/var/www/html/assets
      - ./docker-data/public-files:/var/www/html/files
      - ./docker-data/private-files:/var/www/var/private-files
      - ./docker-data/saas-files:/var/www/var/saas-files
      - ./docker-data/logs:/var/www/var/logs
      - ./docker/production/config.d:/var/www/config/prod.d
      - ./docker/common/config.d:/var/www/config/common.d
    ports:
      - 8080:80
    links:
      - db
      - redis
    environment:
      - JOBS_INTERVAL=${JOBS_INTERVAL}
      - PENDING_PCACHE_RECREATION_INTERVAL=${PENDING_PCACHE_RECREATION_INTERVAL}
      - REDIS_CACHE=${REDIS_CACHE}
      - SESSIONS_SAVE_PATH=${SESSIONS_SAVE_PATH}
      - BUILD_ASSETS=${BUILD_ASSETS}
      - APP_MODE=${APP_MODE}
      - DB_HOST=db
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}

    depends_on:
      - db
      - redis

  redis:
    image: redis:7.4.0-alpine
    restart: unless-stopped
    volumes:
      - ./docker-data/sessions:/data

  db:
    image: softagon/mapasculturais-db:latest
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-StrongP@ssw0rd!123}
      - POSTGRES_USER=${POSTGRES_USER:-default_user}
      - POSTGRES_DB=${POSTGRES_DB:-mapa2025}
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
      - ./docker-data/db-data:/var/lib/postgresql/data