services:
  mapasculturais:
    image: softagon/mapasculturais:main
    restart: unless-stopped
    volumes:
      - /dev/null:/var/www/html/index.php
      - ./docker-data/assets:/var/www/html/assets
      - ./docker-data/public-files:/var/www/html/files
      - ./docker-data/private-files:/var/www/var/private-files
      - ./docker-data/saas-files:/var/www/var/saas-files
      - ./docker-data/sessions:/var/www/var/sessions
      - ./docker-data/logs:/var/www/var/logs
      - ./docker/production/config.d:/var/www/config/prod.d
      - ./docker/common/config.d:/var/www/config/common.d
    ports:
      - 8080:80
    links:
      - db
      - redis
    environment:
      - REDIS_CACHE=${REDIS_CACHE}
      - SESSIONS_SAVE_PATH=${SESSIONS_SAVE_PATH}
      - BUILD_ASSETS=${BUILD_ASSETS}
      - APP_MODE=${APP_MODE}
    depends_on:
      - db
      - redis

  redis:
    image: 	redis:7.4.0-alpine
    command: --maxmemory 1256Mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    volumes:
      - ./docker-data/sessions:/data

  db:
    image: softagon/mapasculturais-db:latest
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
      - ./docker-data/db-data:/var/lib/postgresql/data
