services:
  mapasculturais:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    volumes:
      - ./docker/production/config.d:/var/www/config/prod.d
      - ./docker/common/config.d:/var/www/config/common.d
    environment:
      - JOBS_INTERVAL=${JOBS_INTERVAL}
      - PENDING_PCACHE_RECREATION_INTERVAL=${PENDING_PCACHE_RECREATION_INTERVAL}
      - REDIS_CACHE=${REDIS_CACHE}
      - SESSIONS_SAVE_PATH=${SESSIONS_SAVE_PATH}
      - BUILD_ASSETS=${BUILD_ASSETS}
      - APP_MODE=${APP_MODE}
      # - CEP_TOKEN=${CEP_TOKEN}
    depends_on:
      - db
      - redis
    ports:
      - "80:80"
    links:
      - redis
      - db

  redis:
    image: 	redis:7.4.0-alpine
    command: --maxmemory 1256Mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    volumes:
      - ./docker-data/sessions:/data

  db:
    image: softagon/mapasculturais-db:latest
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-StrongP@ssw0rd!123}
      - POSTGRES_USER=${POSTGRES_USER:-default_user}
      - POSTGRES_DB=${POSTGRES_DB:-mapa2025}
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
      - ./docker-data/db-data:/var/lib/postgresql/data
