services:
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    restart: unless-stopped
    volumes:
      - /dev/null:/var/www/html/index.php
      - ./docker-data/public-files:/var/www/html/files
      - ./docker-data/assets:/var/www/html/assets
    ports:
      - "80:80"
    depends_on:
      - mapasculturais
    links:
      - mapasculturais

  mapasculturais:
    env_file:
      - .env
    build:
      context: ./
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    volumes:
      - ./.env:/.env
      - ./docker-data/assets:/var/www/html/assets
      - ./docker-data/public-files:/var/www/html/files
      - ./docker-data/private-files:/var/www/var/private-files
      - ./docker-data/saas-files:/var/www/var/saas-files
      - ./docker-data/sessions:/var/www/var/sessions
      - ./docker-data/logs:/var/www/var/logs
      - ./docker/production/config.d:/var/www/config/prod.d
      - ./docker/common/config.d:/var/www/config/common.d
    links:
      - db
      - redis
    environment:
      - REDIS_CACHE=redis
      - SESSIONS_SAVE_PATH=tcp://redis:6379
      - BUILD_ASSETS=1
      - APP_MODE=production
    depends_on:
      - db
      - redis

  redis:
    image: redis:7
    command: --maxmemory 1256Mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    volumes:
      - ./docker-data/sessions:/data

  db:
    image: postgis/postgis:17-master
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=mapas
      - POSTGRES_USER=mapas
      - POSTGRES_DB=mapas
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
      - ./docker-data/db-data:/var/lib/postgresql/data
